# Generated by Django 3.1.7 on 2021-03-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000000)),
                ('description', models.TextField(blank=True)),
                ('author', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('started', models.DateField(auto_now_add=True)),
                ('finished', models.DateField(auto_now=True)),
            ],
        ),
    ]
